import type { Business } from "./types";

/**
 * Second layer of the engine: the actual business, gated on real
 * constraints (capital, weekly hours, comfort with selling).
 */
export const businesses: Business[] = [
  // ---------------- BUILDER ----------------
  {
    id: "ai-automation-agency",
    archetype: "builder",
    name: "AI Automation Agency",
    type: "Service",
    reqCapital: 10000,
    reqHours: 10,
    reqSales: 1,
    prefs: ["tech", "online", "agency", "service", "unsure"],
    capitalRange: "₹15,000 to ₹40,000",
    model:
      "You automate boring back-office work for small Indian businesses — WhatsApp enquiry handling, quotation follow-ups, report generation, CRM data entry — using existing tools instead of writing software from scratch. You charge a setup fee plus a monthly retainer to keep the automations running.",
    customers: ["Digital agencies and consultancies (20-100 people)", "Clinics, coaching centres and real estate firms", "D2C brands drowning in manual order and support work"],
    firstOffer:
      "One automation, fixed scope: \"I will connect your website enquiries to WhatsApp and your CRM, with auto follow-ups for 7 days.\" ₹25,000 setup, delivered in 10 days.",
    pricing: "₹25,000 setup + ₹8,000 to ₹15,000 per month for maintenance. Later, bundle 3 automations as a ₹40,000 package.",
    firstCustomer:
      "Your own professional network. Message 20 ex-colleagues and founders you already know on LinkedIn and WhatsApp with one line: \"I'm automating enquiry follow-ups for small businesses. Can I show you a 10 minute demo of your process?\"",
    firstGoal: "1 paying client",
    sevenDays: [
      "Pick one process you will automate (start with lead follow-up).",
      "Rebuild that automation once for a fake business so you have a demo.",
      "Record a 3 minute screen recording of the demo.",
      "List 40 businesses that clearly have this problem.",
      "Write one outreach message and send it to 20 of them.",
      "Book 3 conversations for next week.",
      "Decide your fixed price and stop discounting it.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Define one automation offer and build the demo." },
      { week: "Week 2", task: "Do 10 discovery calls; map one real client's process." },
      { week: "Week 3", task: "Close one paid pilot at your fixed price." },
      { week: "Week 4", task: "Deliver it, record the before/after numbers, ask for a referral." },
    ],
    avoid: [
      { name: "Building a full SaaS product now", why: "It needs 6-9 months of your evenings before the first rupee arrives." },
      { name: "A local food or retail outlet", why: "It is capital heavy and needs your physical presence daily, which your job does not allow." },
      { name: "Dropshipping", why: "It is a paid-ads game, not a skills game — your technical edge counts for nothing there." },
    ],
  },
  {
    id: "micro-saas",
    archetype: "builder",
    name: "Micro SaaS Product",
    type: "Product",
    reqCapital: 50000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["tech", "online", "product", "unsure"],
    capitalRange: "₹50,000 to ₹1,50,000",
    model:
      "You build one narrow software tool for one specific job in one industry, and charge a small monthly fee. Small scope, single problem, no investors, no team. Revenue comes from 100-300 customers paying ₹1,000 to ₹3,000 a month.",
    customers: ["One specific professional group (CAs, gyms, clinics, recruiters)", "Small agencies with a repeating internal workflow", "Sellers on a platform (Amazon, Shopify, Zoho) with an unmet need"],
    firstOffer: "A paid beta: ₹999 per month for the first 20 users, with onboarding done by you personally over a call.",
    pricing: "₹999 to ₹2,999 per month per account, billed annually where possible so cash comes in early.",
    firstCustomer:
      "Communities where your users already complain — industry WhatsApp groups, subreddits, LinkedIn comment sections. Solve one person's problem publicly, then charge the next five.",
    firstGoal: "10 paying users",
    sevenDays: [
      "Choose one industry you already understand from your job.",
      "Interview 5 people from it about their most repetitive weekly task.",
      "Write down the single feature you will build — one screen only.",
      "Build a clickable prototype, not the full product.",
      "Show it to those same 5 people and ask what they would pay.",
      "Collect 3 pre-payments or written commitments.",
      "Only then start building the real version.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Pick the niche and validate the problem with 5 interviews." },
      { week: "Week 2", task: "Ship a painfully small v1 that solves one task." },
      { week: "Week 3", task: "Onboard 5 users personally and watch them use it." },
      { week: "Week 4", task: "Charge them. Fix only what blocks payment." },
    ],
    avoid: [
      { name: "A marketplace", why: "Two-sided businesses need funding and years of liquidity building." },
      { name: "Anything requiring daily physical operations", why: "Your weekly hours cannot cover it alongside a job." },
      { name: "Agency work you secretly don't want", why: "If client calls drain you, retainers will make you quit in month three." },
    ],
  },
  {
    id: "internal-tools-freelance",
    archetype: "builder",
    name: "Internal Tools & Dashboard Studio",
    type: "Service",
    reqCapital: 10000,
    reqHours: 5,
    reqSales: 0,
    prefs: ["tech", "online", "service", "agency", "unsure"],
    capitalRange: "₹5,000 to ₹20,000",
    model:
      "You build the unglamorous internal tools companies never prioritise: ops dashboards, Excel-to-app conversions, reporting automations, admin panels. Project based, remote, and you can do most of it after 8pm.",
    customers: ["Funded startups with a 3-person ops team", "Traditional SMEs still running on Excel", "Agencies that need client reporting dashboards"],
    firstOffer: "\"Your monthly MIS report, automated into a live dashboard in 2 weeks.\" ₹35,000 fixed price.",
    pricing: "₹30,000 to ₹80,000 per project, or ₹1,200 per hour for small changes. Keep a ₹6,000/month support plan.",
    firstCustomer: "Ex-colleagues who are now managers. They have budget, they know your work, and they hate their reporting.",
    firstGoal: "1 paid project",
    sevenDays: [
      "Write down 3 internal tools you have already built at work.",
      "Turn one into a screenshot-based portfolio page.",
      "Set one fixed price for one fixed deliverable.",
      "Message 15 ex-colleagues who now manage teams.",
      "Offer a free 20 minute process review, not a sales call.",
      "Do 3 of those reviews.",
      "Send one proposal before the week ends.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Package one deliverable with one price." },
      { week: "Week 2", task: "Run 5 free process reviews with warm contacts." },
      { week: "Week 3", task: "Send 3 proposals; close one." },
      { week: "Week 4", task: "Deliver, get a written testimonial, raise your price 20%." },
    ],
    avoid: [
      { name: "Low-priced freelance marketplaces", why: "You will compete on hourly rates and stay stuck at ₹300 an hour." },
      { name: "Inventory businesses", why: "Your capital is better spent on nothing at all in a service business." },
      { name: "Content-first businesses", why: "Building an audience takes months; you can bill next week instead." },
    ],
  },

  // ---------------- SELLER ----------------
  {
    id: "b2b-lead-gen",
    archetype: "seller",
    name: "B2B Lead Generation Agency",
    type: "Service",
    reqCapital: 10000,
    reqHours: 5,
    reqSales: 1,
    prefs: ["agency", "service", "online", "unsure"],
    capitalRange: "₹15,000 to ₹40,000",
    model:
      "You find qualified buyers for businesses that sell high-ticket services, and hand over booked appointments. Cold email, LinkedIn and WhatsApp outreach done on behalf of the client. No product, no inventory, no office.",
    customers: ["Clinics and dental chains", "Coaching and edtech businesses", "Local service businesses — interiors, solar, real estate"],
    firstOffer: "\"30 qualified appointments in 60 days or you don't pay the second month.\" ₹30,000 per month, one niche only.",
    pricing: "₹25,000 to ₹50,000 monthly retainer, or ₹800 to ₹2,000 per qualified appointment once you know your numbers.",
    firstCustomer:
      "Pick one niche and message 50 owners directly. Your pitch is proof, not polish: run the outreach for one business free for 10 days and show the booked calls.",
    firstGoal: "3 clients",
    sevenDays: [
      "Choose exactly one niche you understand.",
      "Build a list of 200 businesses in that niche.",
      "Write one 4-line outreach message.",
      "Set up a ₹1,500 email/LinkedIn tool stack.",
      "Send 100 messages.",
      "Book 5 conversations.",
      "Offer one free 10-day pilot to the warmest lead.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Pick the niche, build the list, define the offer." },
      { week: "Week 2", task: "Run a free pilot for one business and log every booked call." },
      { week: "Week 3", task: "Convert the pilot into a paid retainer." },
      { week: "Week 4", task: "Use that result as a case study to close client two and three." },
    ],
    avoid: [
      { name: "Building a SaaS tool", why: "Your money comes from conversations, not from months of silent building." },
      { name: "A café or restaurant", why: "High capital, thin margins, and it needs you on site every evening." },
      { name: "Faceless content pages", why: "Ad revenue is slow and unpredictable compared to selling a service you can start today." },
    ],
  },
  {
    id: "recruitment-agency",
    archetype: "seller",
    name: "Niche Recruitment Agency",
    type: "Service",
    reqCapital: 10000,
    reqHours: 10,
    reqSales: 2,
    prefs: ["service", "agency", "online", "unsure"],
    capitalRange: "₹10,000 to ₹35,000",
    model:
      "You hire for one role type in one industry — the roles you already understand from your own career. Companies pay 8.33% of annual CTC per closed hire. Zero inventory, and your existing network is the starting inventory.",
    customers: ["Startups hiring 5-20 people a year", "Mid-size IT services and BPO firms", "Growing D2C and BFSI teams"],
    firstOffer: "\"First shortlist in 72 hours, you pay only on joining.\" 8.33% of annual CTC.",
    pricing: "8.33% of CTC per hire (₹50,000 to ₹1,50,000 typical), or ₹40,000 per month retained for 2 roles.",
    firstCustomer: "Hiring managers you already know. One WhatsApp message: \"Which role has been open the longest? Let me send you 3 profiles free.\"",
    firstGoal: "1 closed hire",
    sevenDays: [
      "Pick one role you can judge properly (e.g. backend engineers, B2B sales).",
      "List 30 companies hiring for it right now.",
      "Build a candidate pool of 50 from your network and LinkedIn.",
      "Message 20 hiring managers with a free 3-profile offer.",
      "Send one real shortlist.",
      "Fix your fee and your terms in writing.",
      "Set up a simple tracker for candidates and stages.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Choose role + industry; build the first candidate pool." },
      { week: "Week 2", task: "Get 3 companies to accept free shortlists." },
      { week: "Week 3", task: "Sign terms with 2 of them." },
      { week: "Week 4", task: "Push one candidate through to offer stage." },
    ],
    avoid: [
      { name: "Generalist hiring for anyone", why: "Without a niche you cannot judge candidates and clients will not trust you." },
      { name: "Product businesses", why: "Your money is in relationships and speed, not in inventory risk." },
      { name: "Paid ads businesses", why: "You do not need ad spend when your network already has demand." },
    ],
  },
  {
    id: "sales-outsourcing",
    archetype: "seller",
    name: "Outsourced Sales / Channel Partner",
    type: "Service",
    reqCapital: 25000,
    reqHours: 20,
    reqSales: 3,
    prefs: ["service", "local", "agency", "unsure"],
    capitalRange: "₹25,000 to ₹75,000",
    model:
      "You become the sales arm for products you don't own — SaaS tools, financial products, equipment, building materials — earning commission plus a base retainer. You keep the customer relationship, the company keeps the product.",
    customers: ["SaaS companies wanting an India channel", "Manufacturers without a sales team in your city", "Insurance, lending and wealth product companies"],
    firstOffer: "\"I will close ₹5 lakh of business in 60 days for 15% commission and a small retainer.\"",
    pricing: "15% to 30% commission + ₹20,000 to ₹40,000 monthly retainer once you have proof.",
    firstCustomer: "Companies already advertising for sales staff in your city — they have demand and no bandwidth.",
    firstGoal: "₹5 lakh closed value",
    sevenDays: [
      "Pick one product category you can explain in 60 seconds.",
      "Find 15 companies selling it without a strong India team.",
      "Write a one-page partner proposal with clear commission terms.",
      "Send it to all 15.",
      "Pick the one with the best margin and sign a simple agreement.",
      "Build a buyer list of 100 in your city.",
      "Make the first 20 calls.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Choose the product and sign one partnership." },
      { week: "Week 2", task: "Build the buyer list and start outreach." },
      { week: "Week 3", task: "Run 15 demos or meetings." },
      { week: "Week 4", task: "Close the first two deals and renegotiate for a retainer." },
    ],
    avoid: [
      { name: "Building your own product first", why: "You would be paying for months of development before using the skill you already have." },
      { name: "Content businesses", why: "Your conversion happens in conversations, not in comment sections." },
      { name: "Heavy inventory distribution", why: "Start commission-only until you know which product actually moves." },
    ],
  },

  // ---------------- CONSULTANT ----------------
  {
    id: "industry-consulting",
    archetype: "consultant",
    name: "Specialist Consulting Practice",
    type: "Service",
    reqCapital: 10000,
    reqHours: 5,
    reqSales: 0,
    prefs: ["service", "online", "unsure", "agency"],
    capitalRange: "₹5,000 to ₹25,000",
    model:
      "You sell the specific judgement you have built at work — process fixes, audits, system setup, review retainers — to companies smaller than your employer. One person, no team, no office, project fees.",
    customers: ["SMEs with 20-200 employees in your industry", "Funded startups without a senior person in your function", "Family businesses professionalising operations"],
    firstOffer: "A paid diagnostic: \"2-week audit of your <your function> with a 10-point fix list.\" ₹25,000.",
    pricing: "₹25,000 diagnostic, then ₹40,000 to ₹80,000 per implementation project, or ₹20,000/month advisory retainer.",
    firstCustomer:
      "Your own professional network — vendors, ex-managers, clients you have worked with. They already know your competence, which is 80% of consulting sales.",
    firstGoal: "1 paid diagnostic",
    sevenDays: [
      "Write the single problem you fix, in the words your buyer uses.",
      "Package a 2-week paid diagnostic with a fixed price.",
      "List 25 people in your network who own or run something.",
      "Send 25 personal messages — no pitch, just a question about that problem.",
      "Have 5 conversations.",
      "Send 2 one-page proposals.",
      "Open a separate bank account for the business.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Define one problem, one deliverable, one price." },
      { week: "Week 2", task: "Have 10 network conversations." },
      { week: "Week 3", task: "Close one paid diagnostic." },
      { week: "Week 4", task: "Deliver it and convert into an implementation project." },
    ],
    avoid: [
      { name: "Capital-heavy local businesses", why: "Your edge is knowledge; spending ₹5 lakh on setup adds risk without adding advantage." },
      { name: "Free advice to build goodwill", why: "Free work attracts clients who will never pay, and it eats your only 5 hours." },
      { name: "Courses before clients", why: "Sell the service first — the course writes itself from real client problems." },
    ],
  },
  {
    id: "corporate-training",
    archetype: "consultant",
    name: "Corporate Training & Upskilling",
    type: "Service",
    reqCapital: 10000,
    reqHours: 10,
    reqSales: 1,
    prefs: ["service", "online", "content", "unsure"],
    capitalRange: "₹10,000 to ₹30,000",
    model:
      "You deliver practical workshops to company teams on the skill you use daily — Excel and analytics, B2B sales, communication, tooling, compliance. Half-day and two-day formats, billed per batch, mostly on weekends.",
    customers: ["L&D teams at IT and BPO companies", "Engineering and B-school placement cells", "Startups onboarding new sales or ops batches"],
    firstOffer: "\"A 4-hour hands-on workshop for up to 25 people, with a workbook.\" ₹35,000 per batch.",
    pricing: "₹30,000 to ₹60,000 per batch. Cohort version for individuals: ₹4,999 per seat, 20 seats.",
    firstCustomer: "HR and L&D contacts inside your own company's vendor and partner network. Offer one free pilot batch in exchange for a testimonial and a referral.",
    firstGoal: "2 paid batches",
    sevenDays: [
      "Choose one skill and one audience.",
      "Build a 4-hour outline with 3 practical exercises.",
      "Make a one-page brochure with outcomes, not topics.",
      "Message 20 HR / L&D / placement contacts.",
      "Run one free pilot with 10 people from your network.",
      "Collect written feedback and 2 referrals.",
      "Quote your first paid batch.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Build the workshop and the brochure." },
      { week: "Week 2", task: "Run a free pilot and collect proof." },
      { week: "Week 3", task: "Pitch 15 L&D contacts with that proof." },
      { week: "Week 4", task: "Deliver the first paid batch." },
    ],
    avoid: [
      { name: "Recorded course platforms first", why: "Recorded content without a reputation sells to nobody." },
      { name: "Physical training centres", why: "Rent before revenue is the fastest way to lose your savings." },
      { name: "Paid-ads-led coaching", why: "It needs ₹1 lakh+ of ad testing before you learn anything." },
    ],
  },
  {
    id: "career-services",
    archetype: "consultant",
    name: "Career & Hiring Advisory",
    type: "Service",
    reqCapital: 10000,
    reqHours: 5,
    reqSales: 0,
    prefs: ["service", "online", "content", "unsure"],
    capitalRange: "₹5,000 to ₹20,000",
    model:
      "You help working professionals move jobs — positioning, resume, interview preparation, salary negotiation — for a fixed fee per person. Done on calls in the evening, entirely online, no capital.",
    customers: ["2-8 year experience professionals in your own function", "Final year students from tier 2/3 colleges", "Returning-to-work professionals"],
    firstOffer: "\"Interview-ready in 3 sessions\" — positioning, resume rewrite, one mock interview. ₹4,999.",
    pricing: "₹4,999 per person, ₹12,999 for a 6-week package, ₹1,499 for a single mock interview.",
    firstCustomer: "Juniors and peers who already ask you for advice. Post one honest LinkedIn note about hiring in your field and let the DMs come.",
    firstGoal: "5 paying clients",
    sevenDays: [
      "Define who exactly you help — one function, one experience band.",
      "Write the 3-session structure and price it.",
      "Rewrite one friend's resume for free and document the result.",
      "Post one useful LinkedIn note about hiring in your field.",
      "Reply to every DM with a paid offer, not free advice.",
      "Do 3 discovery calls.",
      "Take your first ₹4,999.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Package the offer and get one free proof case." },
      { week: "Week 2", task: "Post 3 times; collect enquiries." },
      { week: "Week 3", task: "Convert 3 paying clients." },
      { week: "Week 4", task: "Deliver, gather results, raise the price." },
    ],
    avoid: [
      { name: "A large placement-guarantee program", why: "Guaranteeing outcomes you don't control creates refunds and reputation damage." },
      { name: "Inventory or local setups", why: "You have very little capital; keep this a zero-inventory business." },
      { name: "Building an app for it", why: "Your service works fine over a call; software adds cost, not revenue." },
    ],
  },

  // ---------------- CREATOR ----------------
  {
    id: "content-agency",
    archetype: "creator",
    name: "Content & Social Media Agency",
    type: "Service",
    reqCapital: 10000,
    reqHours: 10,
    reqSales: 1,
    prefs: ["content", "agency", "online", "service", "unsure"],
    capitalRange: "₹15,000 to ₹50,000",
    model:
      "You run content for businesses that know they need it and hate doing it — LinkedIn for founders, Instagram for local brands, short-form video for coaches. Monthly retainer, fixed deliverables, remote.",
    customers: ["Founders and CXOs who want a LinkedIn presence", "Clinics, cafés, gyms and boutiques in your city", "Coaches and consultants selling high-ticket services"],
    firstOffer: "\"12 posts and 8 reels a month, scripted and scheduled.\" ₹30,000 per month.",
    pricing: "₹25,000 to ₹60,000 per month per client. Founder personal branding commands ₹40,000+.",
    firstCustomer: "Businesses whose social accounts have gone quiet. Send them 3 ready-made post ideas before asking for anything.",
    firstGoal: "2 retainer clients",
    sevenDays: [
      "Pick one platform and one industry.",
      "Create a 6-post sample for an imaginary client in that industry.",
      "Build a simple portfolio page or PDF.",
      "Find 40 businesses with dead social accounts.",
      "Send 20 of them 3 free post ideas each.",
      "Book 5 calls.",
      "Quote a monthly retainer, never per post.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Choose the niche and build the sample work." },
      { week: "Week 2", task: "Outreach to 40 businesses with free ideas." },
      { week: "Week 3", task: "Close the first retainer." },
      { week: "Week 4", task: "Deliver month one; hire one freelance editor." },
    ],
    avoid: [
      { name: "Being a full-service agency", why: "Doing everything for everyone kills your margins and your weekends." },
      { name: "Growing only your own page first", why: "Client retainers pay now; your own audience can grow alongside." },
      { name: "Physical studio setup", why: "Phone plus one mic is enough for the first six months." },
    ],
  },
  {
    id: "ugc-studio",
    archetype: "creator",
    name: "UGC & Performance Creative Studio",
    type: "Service",
    reqCapital: 25000,
    reqHours: 10,
    reqSales: 1,
    prefs: ["content", "online", "agency", "product", "unsure"],
    capitalRange: "₹25,000 to ₹60,000",
    model:
      "You produce the ad creatives D2C brands burn through every month — talking-head UGC, unboxings, hook variations for Meta ads. You are paid per creative batch, with performance as your selling point.",
    customers: ["D2C brands spending ₹2 lakh+ per month on ads", "Performance marketing agencies needing creative supply", "App and edtech companies running Meta ads"],
    firstOffer: "\"10 ad-ready UGC videos with 3 hook variations each, in 12 days.\" ₹40,000.",
    pricing: "₹3,000 to ₹6,000 per video, or ₹40,000 to ₹90,000 per monthly batch.",
    firstCustomer: "Brands whose ads you already see repeatedly on Instagram — they have budget. Send an unsolicited sample video of their product.",
    firstGoal: "1 brand on retainer",
    sevenDays: [
      "Study 30 Indian D2C ads and note the hooks that repeat.",
      "Shoot 3 spec videos for brands you like.",
      "Set up a portfolio of those 3 videos.",
      "Find 25 brands running ads continuously.",
      "Send 15 of them your spec video.",
      "Build a list of 5 freelance creators you can rope in.",
      "Price your first batch and hold the price.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Build spec work and a creator bench." },
      { week: "Week 2", task: "Outreach with unsolicited samples." },
      { week: "Week 3", task: "Close one paid batch." },
      { week: "Week 4", task: "Deliver and report which creative performed best." },
    ],
    avoid: [
      { name: "Starting your own D2C brand now", why: "Inventory plus ad spend is the most expensive way to learn this market." },
      { name: "Paying for expensive gear upfront", why: "A phone, light and lapel mic produce ads that convert." },
      { name: "Retainers without creative limits", why: "Unlimited revisions will consume every evening you have." },
    ],
  },
  {
    id: "niche-media",
    archetype: "creator",
    name: "Niche Newsletter / Media Business",
    type: "Content",
    reqCapital: 10000,
    reqHours: 5,
    reqSales: 0,
    prefs: ["content", "online", "unsure"],
    capitalRange: "₹5,000 to ₹25,000",
    model:
      "You publish for one specific professional audience you already belong to, and monetise through sponsorships, a paid tier and later a product. Slow to start, but it compounds and needs almost no money.",
    customers: ["Sponsors selling to your audience (tools, recruiters, brands)", "Paying subscribers wanting deeper analysis", "Companies wanting to hire from your readership"],
    firstOffer: "Free weekly newsletter for 8 weeks, then a ₹499/month paid tier with deep dives and a jobs board.",
    pricing: "₹25,000 to ₹75,000 per sponsored issue at 5,000+ subscribers; ₹499/month for paid members.",
    firstCustomer: "Your first 200 subscribers come from your own LinkedIn and WhatsApp groups, not from ads.",
    firstGoal: "500 subscribers",
    sevenDays: [
      "Choose one audience and one promise for the newsletter.",
      "Set up a free publishing tool.",
      "Write and publish issue one — do not wait for perfection.",
      "Share it with 5 relevant WhatsApp and LinkedIn groups.",
      "Ask 20 colleagues to subscribe personally.",
      "Plan the next 4 issues.",
      "Commit to a fixed publishing day.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Publish issue one and get the first 100 subscribers." },
      { week: "Week 2", task: "Publish weekly; test two headline styles." },
      { week: "Week 3", task: "Cross-post with 2 other creators in your niche." },
      { week: "Week 4", task: "Reach 500 subscribers and approach your first sponsor." },
    ],
    avoid: [
      { name: "Monetising with ads too early", why: "Below 3,000 subscribers, sponsors pay too little to matter." },
      { name: "Daily publishing", why: "With 5 hours a week, weekly is the only rhythm you will sustain." },
      { name: "Capital-heavy businesses", why: "Your asset here is attention, not assets — keep the costs near zero." },
    ],
  },

  // ---------------- OPERATOR ----------------
  {
    id: "managed-home-services",
    archetype: "operator",
    name: "Managed Home Services",
    type: "Service",
    reqCapital: 50000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["local", "service", "unsure"],
    capitalRange: "₹50,000 to ₹1,50,000",
    model:
      "You do not do the work yourself — you organise it. Deep cleaning, pest control, painting, appliance repair delivered through a trained vendor bench, with your brand handling quality, scheduling and payment.",
    customers: ["Apartment societies and gated communities", "Rental and property management firms", "Working couples in your city"],
    firstOffer: "\"Full 2BHK deep clean, 4 hours, fixed price, re-clean free if unhappy.\" ₹2,999.",
    pricing: "₹2,999 to ₹7,999 per job at 35-45% gross margin; ₹12,000 per year for a 4-visit annual plan.",
    firstCustomer: "Two apartment societies near your home. One weekend demo at the clubhouse plus a WhatsApp group offer beats any ad.",
    firstGoal: "20 paid jobs",
    sevenDays: [
      "Pick one service and one 5 km radius.",
      "Meet 8 vendors or crews; shortlist 2.",
      "Fix your price, scope and quality checklist.",
      "Get into 3 society WhatsApp groups.",
      "Run one discounted launch weekend.",
      "Deliver 3 jobs yourself on site to learn the process.",
      "Collect reviews and photos from every job.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Lock one service, one area, two crews." },
      { week: "Week 2", task: "Launch in 3 societies; complete 5 jobs." },
      { week: "Week 3", task: "Fix quality gaps; introduce the annual plan." },
      { week: "Week 4", task: "Reach 20 jobs and hire a coordinator for calls." },
    ],
    avoid: [
      { name: "Multiple services at once", why: "Each service has different crews and quality issues; you will fail at all of them." },
      { name: "An app before demand", why: "WhatsApp and a spreadsheet run this business fine until 100 jobs a month." },
      { name: "A pure online business", why: "Your strength is execution and coordination, which offline work rewards more." },
    ],
  },
  {
    id: "logistics-coordination",
    archetype: "operator",
    name: "Logistics & Fulfilment Coordination",
    type: "Service",
    reqCapital: 100000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["local", "service", "product", "unsure"],
    capitalRange: "₹1,00,000 to ₹3,00,000",
    model:
      "You handle storage, packing and dispatch for small D2C brands that have outgrown their bedroom but cannot afford a warehouse. You charge per order handled plus storage rent.",
    customers: ["D2C brands doing 300-3,000 orders a month", "Instagram sellers and small exporters", "Regional distributors needing last-mile support"],
    firstOffer: "\"Pick, pack and dispatch your orders same day.\" ₹35 per order + ₹3,000 per rack per month.",
    pricing: "₹25 to ₹60 per order, ₹3,000 to ₹8,000 monthly storage, plus courier margin.",
    firstCustomer: "Small brands in your city already complaining about delays on Instagram. Offer to run 100 orders at cost.",
    firstGoal: "2 brands, 500 orders/month",
    sevenDays: [
      "Find a 300-500 sq ft space you can rent monthly.",
      "Get courier aggregator rates from 3 providers.",
      "Cost one order end to end and set your price.",
      "List 30 small brands in your city.",
      "Pitch 10 with a 100-order trial.",
      "Hire one packer on a daily wage.",
      "Set up a simple order tracker.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Lock space, courier rates and unit economics." },
      { week: "Week 2", task: "Run a free trial for one brand." },
      { week: "Week 3", task: "Sign the first paid contract." },
      { week: "Week 4", task: "Add brand two and measure SLA daily." },
    ],
    avoid: [
      { name: "Signing a long lease early", why: "Take month-to-month space until you have two paying brands." },
      { name: "Buying your own delivery vehicles", why: "Aggregators are cheaper until you cross serious volume." },
      { name: "A content or personal brand business", why: "It would not use your operational strength at all." },
    ],
  },
  {
    id: "process-ops-service",
    archetype: "operator",
    name: "Back-Office Operations Service",
    type: "Service",
    reqCapital: 10000,
    reqHours: 10,
    reqSales: 1,
    prefs: ["service", "online", "agency", "unsure"],
    capitalRange: "₹10,000 to ₹40,000",
    model:
      "You take over the repetitive operational work small companies hate — order processing, invoicing, vendor follow-ups, GST document collection, CRM hygiene — as a monthly managed service delivered remotely.",
    customers: ["Small D2C and ecommerce brands", "CA firms and consultancies with document chaos", "Agencies without an ops person"],
    firstOffer: "\"Your order-to-invoice process, run by us, daily.\" ₹20,000 per month.",
    pricing: "₹15,000 to ₹45,000 per month per client, one ops assistant covering 3 clients.",
    firstCustomer: "Founders in your network who are personally still doing invoices at 11pm.",
    firstGoal: "2 monthly clients",
    sevenDays: [
      "Choose one process you can document end to end.",
      "Write the SOP in 10 steps.",
      "Price a monthly retainer.",
      "Message 20 small business owners you know.",
      "Offer a free one-week process audit.",
      "Complete 3 audits.",
      "Send 2 retainer proposals.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Document the SOP and price the retainer." },
      { week: "Week 2", task: "Run 3 free audits with warm contacts." },
      { week: "Week 3", task: "Close one retainer and run it yourself." },
      { week: "Week 4", task: "Hire a part-time assistant; add client two." },
    ],
    avoid: [
      { name: "Hiring a team before clients", why: "Salaries before revenue is the classic first-business mistake." },
      { name: "Inventory businesses", why: "Your capital is limited; services keep the risk near zero." },
      { name: "Chasing large enterprises", why: "Their procurement cycles are longer than your patience and runway." },
    ],
  },

  // ---------------- PRODUCT ----------------
  {
    id: "niche-d2c",
    archetype: "product",
    name: "Niche D2C Brand",
    type: "Product",
    reqCapital: 100000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["product", "online", "unsure"],
    capitalRange: "₹1,00,000 to ₹3,00,000",
    model:
      "You sell one focused product line to one clearly defined customer — not a general store. Manufacture through contract suppliers, sell on your own site plus one marketplace, and grow with creative-led Meta ads.",
    customers: ["A specific community (new parents, pet owners, gym goers, hostellers)", "Gifting and corporate bulk buyers", "Marketplace shoppers searching your category"],
    firstOffer: "One hero SKU, one size, one price. ₹899 with free shipping and a no-questions return.",
    pricing: "Keep a 65%+ gross margin: ₹899 selling price on ₹280 landed cost. Bundles at ₹1,699.",
    firstCustomer: "Start with 50 units and sell them by hand — WhatsApp groups, one local store, one Instagram page — before spending on ads.",
    firstGoal: "First 100 orders",
    sevenDays: [
      "Choose one product for one specific customer.",
      "Get quotes from 5 suppliers; order samples.",
      "Cost the product landed, including shipping and returns.",
      "Build a one-product store page.",
      "Shoot photos and 3 videos with your phone.",
      "Pre-sell 20 units to people you know.",
      "Only then place your first 50-100 unit order.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Lock product, supplier and unit economics." },
      { week: "Week 2", task: "Launch the store; sell the first 20 units manually." },
      { week: "Week 3", task: "Spend ₹500/day on ads and test 5 creatives." },
      { week: "Week 4", task: "Review CAC vs margin honestly; scale or change the product." },
    ],
    avoid: [
      { name: "Launching 10 SKUs at once", why: "Inventory gets stuck and you never learn which product actually sells." },
      { name: "Large first production runs", why: "Unsold stock is the most common way first-time founders lose their savings." },
      { name: "Service businesses you have no interest in", why: "If you want a product, a retainer business will feel like a second job." },
    ],
  },
  {
    id: "subscription-box",
    archetype: "product",
    name: "Subscription Product Business",
    type: "Product",
    reqCapital: 100000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["product", "online", "unsure", "content"],
    capitalRange: "₹1,00,000 to ₹2,50,000",
    model:
      "You sell a consumable or curated product on a monthly plan, so one sale produces repeat revenue — coffee, pet treats, snacks, stationery, skincare refills. Predictable cash flow, tighter operations.",
    customers: ["Urban professionals with a recurring habit", "Pet parents and hobby communities", "Corporate gifting for employee engagement"],
    firstOffer: "\"Monthly plan, delivered on the 1st, cancel anytime.\" ₹699 per month.",
    pricing: "₹699 to ₹1,499 per month with 60%+ margin; 3-month prepaid plan at 10% off to fund inventory.",
    firstCustomer: "Your first 30 subscribers should be people you can call by name. Run a WhatsApp-only launch.",
    firstGoal: "50 subscribers",
    sevenDays: [
      "Choose the consumable and the monthly ritual around it.",
      "Find 3 suppliers who can hold consistent quality.",
      "Cost one month's box including shipping.",
      "Create a simple subscription checkout.",
      "Sell 10 prepaid 3-month plans to your network.",
      "Pack and ship those 10 yourself.",
      "Ask every subscriber what almost stopped them from buying.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Lock product, supplier and price." },
      { week: "Week 2", task: "Sell the first 20 subscriptions manually." },
      { week: "Week 3", task: "Ship month one; measure churn reasons." },
      { week: "Week 4", task: "Reach 50 subscribers; test one paid channel." },
    ],
    avoid: [
      { name: "Curated boxes with new items every month", why: "Sourcing costs kill you; a repeatable consumable is far easier to run." },
      { name: "Discount-led growth", why: "Subscribers acquired on discounts churn in month two." },
      { name: "Low-capital service businesses", why: "Only if you actually want a product business — otherwise a service earns faster." },
    ],
  },
  {
    id: "specialised-consumer-product",
    archetype: "product",
    name: "Specialised Consumer Product (Pet / Office / Home)",
    type: "Product",
    reqCapital: 500000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["product", "local", "online", "unsure"],
    capitalRange: "₹5,00,000 to ₹12,00,000",
    model:
      "You build a product brand in a category with real repeat demand and weak Indian options — pet care, ergonomic office goods, home organisation. Own tooling or private labelling, distribution through marketplaces plus modern retail.",
    customers: ["Marketplace shoppers in your category", "Modern retail and pet/office store chains", "Corporate and institutional bulk buyers"],
    firstOffer: "A flagship product with a 12-month warranty at a price 20% below the imported alternative.",
    pricing: "Keep 55-65% gross margin with MRP set for marketplace fees and returns. Bulk pricing at 30% off list.",
    firstCustomer: "One marketplace listing plus 5 offline stores in your city taken on consignment.",
    firstGoal: "First 300 units sold",
    sevenDays: [
      "Pick the category and study the top 20 listings honestly.",
      "Identify the one complaint that repeats in reviews.",
      "Get quotes from 5 manufacturers.",
      "Order samples and test them yourself for a week.",
      "Register the brand and GST properly.",
      "Plan a first run you can afford to write off.",
      "Line up 5 offline stores for consignment.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Finalise category, complaint to fix, and supplier." },
      { week: "Week 2", task: "Approve samples; register brand and listings." },
      { week: "Week 3", task: "Place a small first run; launch on one marketplace." },
      { week: "Week 4", task: "Push offline consignment; track sell-through weekly." },
    ],
    avoid: [
      { name: "Spending the full capital on run one", why: "Keep at least 50% for marketing and a second, corrected production run." },
      { name: "Competing on price with imports", why: "You will lose; compete on the specific defect customers complain about." },
      { name: "Launching without GST and compliance", why: "Marketplaces will block payouts and you will lose weeks." },
    ],
  },

  // ---------------- COMMUNITY ----------------
  {
    id: "professional-community",
    archetype: "community",
    name: "Paid Professional Community",
    type: "Membership",
    reqCapital: 10000,
    reqHours: 10,
    reqSales: 1,
    prefs: ["online", "content", "service", "unsure"],
    capitalRange: "₹10,000 to ₹40,000",
    model:
      "You run a paid group for one professional niche — referrals, hiring, deals, peer advice — with a monthly call and a curated members list. Revenue from memberships, sponsors and later events.",
    customers: ["Mid-career professionals in one function", "Freelancers and agency owners needing leads", "Vendors who want access to that group (sponsors)"],
    firstOffer: "Founding membership: ₹2,999 for 6 months, capped at 50 members, with 2 live calls a month.",
    pricing: "₹499 to ₹999 per month, or ₹4,999 a year. Sponsor slots at ₹25,000 a quarter.",
    firstCustomer: "The 30 people you would personally want in the room. Invite them one by one, not through a public post.",
    firstGoal: "50 founding members",
    sevenDays: [
      "Define the niche and the one outcome members get.",
      "Write down the 30 people you want first.",
      "Set up a WhatsApp community plus a simple payment link.",
      "Invite 30 people personally.",
      "Run the first live call within the week.",
      "Publish simple rules and a weekly rhythm.",
      "Charge from day one, even if it is ₹499.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Recruit 20 founding members personally." },
      { week: "Week 2", task: "Run 2 calls; create the first member-to-member win." },
      { week: "Week 3", task: "Publish that win and open paid signups." },
      { week: "Week 4", task: "Reach 50 members; approach one sponsor." },
    ],
    avoid: [
      { name: "A free community first", why: "Free groups go silent, and converting them to paid later rarely works." },
      { name: "Building a custom app", why: "WhatsApp plus a payment link is enough for the first 200 members." },
      { name: "Capital-heavy offline businesses", why: "Your asset is relationships; spend time, not money." },
    ],
  },
  {
    id: "events-business",
    archetype: "community",
    name: "Niche Events & Meetups Business",
    type: "Events",
    reqCapital: 50000,
    reqHours: 20,
    reqSales: 2,
    prefs: ["local", "service", "unsure", "online"],
    capitalRange: "₹50,000 to ₹2,00,000",
    model:
      "You run paid, small-format events for one audience — founder dinners, industry meetups, workshops, hobby experiences — earning from tickets plus sponsorships. Repeatable format, city by city.",
    customers: ["Professionals in one industry in your city", "Brands wanting access to that audience", "Venues wanting weekday footfall"],
    firstOffer: "A 40-seat paid meetup: 2 speakers, curated attendees, ₹799 per ticket.",
    pricing: "₹799 to ₹2,499 per ticket; ₹50,000 to ₹1,50,000 per title sponsor once you have run 2 editions.",
    firstCustomer: "Your first 40 attendees come from your own network and 3 WhatsApp communities.",
    firstGoal: "One sold-out edition",
    sevenDays: [
      "Choose the audience and the reason they would leave home.",
      "Lock a venue with a revenue-share or low minimum.",
      "Confirm 2 speakers from your network.",
      "Open ticket sales with a simple form and UPI link.",
      "Personally invite 60 people.",
      "Sell 20 tickets.",
      "Plan the run sheet hour by hour.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Fix format, venue and speakers." },
      { week: "Week 2", task: "Sell 30 tickets through personal invites." },
      { week: "Week 3", task: "Run edition one and film everything." },
      { week: "Week 4", task: "Publish the recap; pre-sell edition two and pitch a sponsor." },
    ],
    avoid: [
      { name: "Large 300-person events", why: "One unsold big event can wipe out your entire capital." },
      { name: "Free events for reach", why: "Free attendees do not show up, and sponsors notice empty chairs." },
      { name: "Online-only products at the start", why: "Your edge is in-person energy; use it before going digital." },
    ],
  },
  {
    id: "niche-marketplace-network",
    archetype: "community",
    name: "Niche Talent / Vendor Network",
    type: "Service",
    reqCapital: 25000,
    reqHours: 10,
    reqSales: 2,
    prefs: ["online", "service", "agency", "unsure"],
    capitalRange: "₹25,000 to ₹60,000",
    model:
      "You become the trusted middle layer between companies and a vetted pool of specialists — designers, video editors, accountants, trainers. You are paid a margin on every engagement you place.",
    customers: ["Startups needing vetted freelancers quickly", "Agencies needing overflow capacity", "SMEs needing a reliable vendor they can call"],
    firstOffer: "\"Tell me the brief, you get 2 vetted specialists in 24 hours. Pay me, I pay them.\"",
    pricing: "25-35% margin on every engagement, or ₹15,000 per placement for longer contracts.",
    firstCustomer: "Founders and managers already asking you \"do you know a good designer?\" — that question is the business.",
    firstGoal: "5 placements",
    sevenDays: [
      "Pick one skill category you can judge.",
      "Vet 15 specialists through a small paid test task.",
      "Fix your margin and payment terms.",
      "Message 25 companies who hire this skill.",
      "Offer to fill one brief within 24 hours.",
      "Complete your first placement.",
      "Collect feedback from both sides.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Build a vetted bench of 15 specialists." },
      { week: "Week 2", task: "Get 5 live briefs from companies." },
      { week: "Week 3", task: "Complete 2 placements and get paid." },
      { week: "Week 4", task: "Standardise contracts; reach 5 placements." },
    ],
    avoid: [
      { name: "Building a two-sided platform", why: "You do not need software; a spreadsheet and WhatsApp work until 50 placements." },
      { name: "Letting clients pay freelancers directly", why: "You lose the margin and the relationship in one move." },
      { name: "Product businesses", why: "Inventory risk adds nothing to a network-based advantage." },
    ],
  },

  // ---------------- LOCAL ----------------
  {
    id: "fitness-service",
    archetype: "local",
    name: "Specialised Fitness / Wellness Studio",
    type: "Local service",
    reqCapital: 500000,
    reqHours: 40,
    reqSales: 1,
    prefs: ["local", "product", "service", "unsure"],
    capitalRange: "₹5,00,000 to ₹15,00,000",
    model:
      "A small-format studio for one modality — strength, pilates, yoga, functional training — running batch memberships instead of annual gym contracts. Revenue depends on trainer quality and retention, not equipment.",
    customers: ["Working professionals within 3 km", "Women-only batches in residential areas", "Corporate wellness tie-ups"],
    firstOffer: "8-week transformation batch, 3 sessions a week, 12 people per batch. ₹7,999.",
    pricing: "₹3,000 to ₹6,000 per month per member; ₹7,999 per 8-week batch; corporate packages at ₹1 lakh per quarter.",
    firstCustomer: "Your own apartment complex and the offices within 2 km. Run free weekend sessions in the park first.",
    firstGoal: "30 paying members",
    sevenDays: [
      "Pick one modality and one 3 km catchment.",
      "Run 2 free outdoor sessions to test demand.",
      "Collect 50 phone numbers of interested people.",
      "Shortlist 3 spaces and 2 trainers.",
      "Pre-sell 10 memberships before signing the lease.",
      "Cost rent, trainer and equipment against realistic member counts.",
      "Only sign the lease if pre-sales cover 3 months of rent.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Test demand with free outdoor batches." },
      { week: "Week 2", task: "Pre-sell 10 memberships; shortlist the space." },
      { week: "Week 3", task: "Sign the space; hire one trainer." },
      { week: "Week 4", task: "Launch with 2 batches; track attendance daily." },
    ],
    avoid: [
      { name: "A full-size gym with heavy equipment", why: "₹30 lakh of equipment with no proven demand is how most fitness businesses die." },
      { name: "Annual discounted memberships", why: "You get cash now and dead members later, with no real retention signal." },
      { name: "Running it while working full time", why: "This business needs presence; do not start until your hours allow it." },
    ],
  },
  {
    id: "pet-care-service",
    archetype: "local",
    name: "Pet Care Services",
    type: "Local service",
    reqCapital: 100000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["local", "service", "product", "unsure"],
    capitalRange: "₹1,00,000 to ₹3,00,000",
    model:
      "Grooming, walking, boarding and training for urban pet parents — a category with fast-growing Indian demand and very few reliable operators. Start mobile (at-home service) before any physical centre.",
    customers: ["Apartment pet parents within 5 km", "Working couples needing daytime walking or boarding", "Vet clinics who can refer grooming"],
    firstOffer: "At-home grooming, fixed price by pet size, ₹999 onwards, with same-week slots.",
    pricing: "₹999 to ₹2,499 per grooming; ₹4,000 per month for daily walks; ₹800 per night boarding.",
    firstCustomer: "Society WhatsApp groups and two vet clinics near you. Pet parents buy on trust and referrals, not ads.",
    firstGoal: "25 repeat customers",
    sevenDays: [
      "Choose one service to start with (grooming is the easiest).",
      "Hire or partner with one experienced groomer.",
      "Buy only the basic mobile grooming kit.",
      "Join 5 society and pet-owner WhatsApp groups.",
      "Run a discounted first weekend with 6 appointments.",
      "Photograph every before-and-after.",
      "Set up a simple booking number and slot calendar.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Lock the service, the groomer and the kit." },
      { week: "Week 2", task: "Complete 10 at-home jobs in 2 societies." },
      { week: "Week 3", task: "Tie up with 2 vet clinics for referrals." },
      { week: "Week 4", task: "Reach 25 customers and launch a monthly plan." },
    ],
    avoid: [
      { name: "A physical pet centre immediately", why: "Rent and fit-out before demand is proven is an avoidable risk." },
      { name: "Boarding without trained staff", why: "One bad incident ends the business's reputation in your city." },
      { name: "Online-only businesses", why: "Your preference for local work fits a service customers can see and trust." },
    ],
  },
  {
    id: "education-centre",
    archetype: "local",
    name: "Focused Education / Coaching Centre",
    type: "Local service",
    reqCapital: 100000,
    reqHours: 20,
    reqSales: 1,
    prefs: ["local", "service", "content", "unsure"],
    capitalRange: "₹1,00,000 to ₹4,00,000",
    model:
      "Small-batch coaching for one specific outcome — one exam, one skill, one grade band — run in a modest space or hybrid mode. Batch fees collected upfront, so working capital stays healthy.",
    customers: ["Parents within 3 km for grade-specific coaching", "Working professionals wanting weekend skill batches", "College students preparing for placements"],
    firstOffer: "12-week batch, 3 classes a week, 15 students per batch, ₹9,999 with a free first week.",
    pricing: "₹8,000 to ₹15,000 per student per batch; weekend professional batches at ₹12,999.",
    firstCustomer: "One free demo class advertised in 3 society groups plus two schools or colleges nearby.",
    firstGoal: "One full batch of 15",
    sevenDays: [
      "Choose one exam, subject or skill with clear local demand.",
      "Design a 12-week syllabus with weekly outcomes.",
      "Book an hourly-rate space or use a hybrid setup.",
      "Run one free demo class for 20 people.",
      "Collect fees from the first 5 students.",
      "Set a fixed batch start date and stick to it.",
      "Ask every parent or student how they found you.",
    ],
    thirtyDays: [
      { week: "Week 1", task: "Finalise syllabus, batch size and price." },
      { week: "Week 2", task: "Run 2 free demos; enrol 8 students." },
      { week: "Week 3", task: "Start the batch; measure attendance and doubts." },
      { week: "Week 4", task: "Fill to 15; collect results and testimonials." },
    ],
    avoid: [
      { name: "A large multi-subject institute", why: "Many subjects means many teachers and no reputation for anything." },
      { name: "Expensive interiors before batch one", why: "Parents pay for results, not for furniture." },
      { name: "Free classes to build numbers", why: "Paid students attend; free students do not, and results suffer." },
    ],
  },
];

export const businessById = (id: string) => businesses.find((b) => b.id === id);
