import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: "q1",
    title: "What do you currently do?",
    hint: "Your day job, not your dream job.",
    options: [
      {
        id: "it",
        label: "IT / Software",
        profession: "IT / Software",
        a: { builder: 4, consultant: 1 },
        s: { builder: 3 },
      },
      {
        id: "finance",
        label: "Finance",
        profession: "Finance",
        a: { consultant: 4, product: 1 },
        s: { builder: 1 },
      },
      { id: "sales", label: "Sales", profession: "Sales", a: { seller: 4, community: 1 }, s: { sales: 3, people: 2 } },
      {
        id: "marketing",
        label: "Marketing",
        profession: "Marketing",
        a: { creator: 4, seller: 1 },
        s: { people: 1 },
      },
      { id: "ops", label: "Operations", profession: "Operations", a: { operator: 4, local: 1 } },
      { id: "hr", label: "HR", profession: "HR", a: { community: 3, consultant: 2 }, s: { people: 2 } },
      { id: "design", label: "Design / Creative", profession: "Design / Creative", a: { creator: 4, product: 1 } },
      { id: "consulting", label: "Consulting", profession: "Consulting", a: { consultant: 4 }, s: { people: 1 } },
      {
        id: "education",
        label: "Education",
        profession: "Education",
        a: { consultant: 2, creator: 2, community: 1 },
        s: { people: 2 },
      },
      { id: "healthcare", label: "Healthcare", profession: "Healthcare", a: { local: 3, operator: 1 } },
      { id: "other", label: "Other", profession: "a corporate role", a: { consultant: 1, operator: 1 } },
    ],
  },
  {
    id: "q2",
    title: "What are you naturally good at?",
    hint: "Pick the one people already ask you for.",
    options: [
      { id: "selling", label: "Selling", a: { seller: 4, local: 1 }, s: { sales: 3 } },
      { id: "talking", label: "Talking to people", a: { community: 3, seller: 2 }, s: { people: 3 } },
      { id: "building", label: "Building things", a: { builder: 4, product: 1 }, s: { builder: 3 } },
      { id: "managing", label: "Managing people", a: { operator: 3, local: 2 }, s: { people: 2 } },
      { id: "numbers", label: "Analyzing numbers", a: { consultant: 3, builder: 1 }, s: { builder: 2 } },
      { id: "content", label: "Creating content", a: { creator: 4 }, s: { independence: 1 } },
      { id: "organizing", label: "Organizing things", a: { operator: 4 } },
      { id: "solving", label: "Solving problems", a: { consultant: 3, builder: 2 }, s: { builder: 1 } },
      { id: "teaching", label: "Teaching", a: { consultant: 3, creator: 1, community: 1 }, s: { people: 2 } },
      { id: "negotiating", label: "Negotiating", a: { seller: 3, product: 1 }, s: { sales: 2 } },
    ],
  },
  {
    id: "q3",
    title: "What kind of work gives you energy?",
    options: [
      { id: "independent", label: "Working independently", a: { builder: 2, creator: 2 }, s: { independence: 3 } },
      { id: "people", label: "Meeting people", a: { community: 3, seller: 2 }, s: { people: 3 } },
      { id: "build", label: "Building things", a: { builder: 3, product: 2 }, s: { builder: 3 } },
      { id: "customers", label: "Finding customers", a: { seller: 4 }, s: { sales: 3 } },
      { id: "teams", label: "Managing teams", a: { operator: 3, local: 2 }, s: { people: 2 } },
      { id: "create", label: "Creating something", a: { creator: 3, product: 2 }, s: { independence: 2 } },
      { id: "research", label: "Researching and analyzing", a: { consultant: 3, builder: 1 }, s: { builder: 2 } },
      { id: "teach", label: "Teaching others", a: { consultant: 2, creator: 2, community: 1 }, s: { people: 2 } },
    ],
  },
  {
    id: "q4",
    title: "What frustrates you most about your job?",
    options: [
      { id: "repetitive", label: "Repetitive work", a: { builder: 2, creator: 1 }, s: { builder: 2 } },
      { id: "manager", label: "My manager", a: { creator: 1, consultant: 1 }, s: { independence: 3 } },
      { id: "politics", label: "Office politics", a: { consultant: 2 }, s: { independence: 3 } },
      { id: "salary", label: "Low salary", a: { seller: 2, product: 1 }, s: { income: 3, sales: 1 } },
      { id: "hours", label: "Long hours", a: { creator: 1, consultant: 1 }, s: { independence: 2 } },
      { id: "autonomy", label: "No autonomy", a: { builder: 1, creator: 2 }, s: { independence: 3, risk: 1 } },
      { id: "growth", label: "No growth", a: { seller: 1, consultant: 2 }, s: { income: 2, risk: 1 } },
      { id: "meaning", label: "I don't feel connected to the work", a: { community: 2, creator: 2 }, s: { people: 1 } },
    ],
  },
  {
    id: "q5",
    title: "How much money could you realistically put in?",
    hint: "Money you can lose without hurting your family.",
    options: [
      { id: "c10", label: "₹10,000", capital: 10000, a: { consultant: 3, seller: 2, creator: 2 }, s: { capital: 0 } },
      { id: "c25", label: "₹25,000", capital: 25000, a: { seller: 2, builder: 2, creator: 1 }, s: { capital: 1 } },
      { id: "c50", label: "₹50,000", capital: 50000, a: { builder: 2, operator: 1, community: 1 }, s: { capital: 2 } },
      { id: "c100", label: "₹1 lakh", capital: 100000, a: { product: 2, operator: 2, local: 2 }, s: { capital: 3, risk: 1 } },
      { id: "c500", label: "₹5 lakh+", capital: 500000, a: { local: 3, product: 3 }, s: { capital: 4, risk: 2 } },
    ],
  },
  {
    id: "q6",
    title: "How much time could you give it initially?",
    options: [
      { id: "h5", label: "5 hours per week", hours: 5, a: { consultant: 3, creator: 1 }, s: { time: 0 } },
      { id: "h10", label: "10 hours per week", hours: 10, a: { seller: 2, consultant: 2, creator: 2 }, s: { time: 1 } },
      { id: "h20", label: "20 hours per week", hours: 20, a: { builder: 2, operator: 2, community: 1 }, s: { time: 2, risk: 1 } },
      { id: "h40", label: "Almost full time", hours: 40, a: { local: 3, product: 2, operator: 2 }, s: { time: 3, risk: 2 } },
    ],
  },
  {
    id: "q7",
    title: "How comfortable are you with selling?",
    options: [
      { id: "s0", label: "I hate selling", salesComfort: 0, a: { builder: 3, creator: 2, product: 1 }, s: { sales: 0 } },
      { id: "s1", label: "I can learn", salesComfort: 1, a: { consultant: 2, operator: 2 }, s: { sales: 1 } },
      { id: "s2", label: "I am comfortable", salesComfort: 2, a: { seller: 2, consultant: 2, community: 1 }, s: { sales: 2 } },
      { id: "s3", label: "I enjoy selling", salesComfort: 3, a: { seller: 4, local: 1 }, s: { sales: 3, income: 1 } },
    ],
  },
  {
    id: "q8",
    title: "What kind of business sounds most attractive?",
    options: [
      { id: "online", label: "Online business", preference: "online", a: { creator: 2, builder: 2 }, s: { independence: 2 } },
      { id: "local", label: "Local business", preference: "local", a: { local: 4, operator: 1 } },
      { id: "service", label: "Service business", preference: "service", a: { consultant: 3, seller: 1, operator: 1 } },
      { id: "productb", label: "Product business", preference: "product", a: { product: 4 }, s: { risk: 1 } },
      { id: "agency", label: "Agency", preference: "agency", a: { seller: 2, creator: 2, builder: 1 } },
      { id: "contentb", label: "Content business", preference: "content", a: { creator: 4 }, s: { independence: 1 } },
      { id: "tech", label: "Technology", preference: "tech", a: { builder: 4 }, s: { builder: 2 } },
      { id: "unsure", label: "I don't know", preference: "unsure", a: { consultant: 1, seller: 1 } },
    ],
  },
  {
    id: "q9",
    title: "What monthly income would make you seriously consider leaving?",
    options: [
      { id: "i30", label: "₹30,000", incomeTarget: 30000, a: { consultant: 2, creator: 1 }, s: { income: 0 } },
      { id: "i50", label: "₹50,000", incomeTarget: 50000, a: { consultant: 2, seller: 1, creator: 1 }, s: { income: 1 } },
      { id: "i100", label: "₹1 lakh", incomeTarget: 100000, a: { seller: 2, builder: 2, operator: 1 }, s: { income: 2 } },
      { id: "i200", label: "₹2 lakh", incomeTarget: 200000, a: { seller: 2, product: 2, builder: 1 }, s: { income: 3, risk: 1 } },
      { id: "i500", label: "₹5 lakh+", incomeTarget: 500000, a: { product: 3, local: 2, builder: 1 }, s: { income: 4, risk: 2 } },
    ],
  },
  {
    id: "q10",
    title: "What matters most to you?",
    options: [
      { id: "freedom", label: "Freedom", a: { creator: 2, consultant: 2 }, s: { independence: 3 } },
      { id: "money", label: "Money", a: { seller: 3, product: 1 }, s: { income: 3, sales: 1 } },
      { id: "meaning", label: "Meaningful work", a: { community: 2, consultant: 2 }, s: { people: 2 } },
      { id: "status", label: "Status", a: { product: 2, builder: 1 }, s: { income: 2, risk: 1 } },
      { id: "own", label: "Building something of my own", a: { builder: 3, product: 2 }, s: { builder: 2, risk: 2 } },
      { id: "exit", label: "Leaving corporate life", a: { consultant: 2, local: 1, creator: 1 }, s: { independence: 3, risk: 1 } },
    ],
  },
];

export const totalQuestions = questions.length;
