import { Company, CompanyGoal, Agent, Ticket } from "./types";

export const DEFAULT_COMPANIES: Company[] = [
  {
    id: "comp-founderfit",
    name: "FounderFit Autonomous Strategy Corp",
    mission:
      "Autonomously diagnose and execute high-impact business solutions using MECE strategy frameworks (Profitability, Market Entry, Growth, Pricing, GTM, and M&A).",
    industry: "Management Consulting & Strategic Operations",
    monthlyBudgetUsd: 500,
    spentBudgetUsd: 42.85,
    createdAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "comp-paperclip-labs",
    name: "Paperclip Autonomous SaaS Labs",
    mission:
      "Ship high-frequency software products, automate technical architecture, and drive autonomous product-led growth with zero human bottleneck.",
    industry: "Enterprise AI & Cloud Software",
    monthlyBudgetUsd: 1200,
    spentBudgetUsd: 114.2,
    createdAt: "2026-02-15T09:30:00Z",
  },
];

export const DEFAULT_GOALS: Record<string, CompanyGoal[]> = {
  "comp-founderfit": [
    {
      id: "goal-ff-1",
      companyId: "comp-founderfit",
      title: "Resolve Q3 Quick-Commerce EBITDA Burn & Dark Store Leaks",
      description:
        "Deconstruct profitability using FMS Value Chain breakdown; identify top 3 contribution margin optimization levers to reach store-level profitability.",
      targetMetric: "Store-level Contribution Margin > +4.5%",
      status: "active",
      progressPct: 65,
    },
    {
      id: "goal-ff-2",
      companyId: "comp-founderfit",
      title: "Design UAE & GCC Cross-Border Market Entry Playbook",
      description:
        "Evaluate STP market attractiveness, regulatory MoH barriers, omnichannel distribution vs JV options for direct-to-consumer scale.",
      targetMetric: "$5M ARR in GCC within 18 Months",
      status: "active",
      progressPct: 40,
    },
    {
      id: "goal-ff-3",
      companyId: "comp-founderfit",
      title: "Value-Based SaaS Pricing Overhaul & Enterprise Tier Launch",
      description:
        "Transition usage-based API platform into 3-tier pricing matrix with multi-seat governance and 40% margin uplift.",
      targetMetric: "Net Revenue Retention > 125%",
      status: "active",
      progressPct: 20,
    },
  ],
  "comp-paperclip-labs": [
    {
      id: "goal-pcl-1",
      companyId: "comp-paperclip-labs",
      title: "Autonomous Heartbeat Agent Orchestration Engine v2.0",
      description:
        "Implement atomic ticket checkout, token budget governance, and multi-agent delegation pipelines.",
      targetMetric: "99.9% Zero-Collision Ticket Checkout",
      status: "active",
      progressPct: 80,
    },
    {
      id: "goal-pcl-2",
      companyId: "comp-paperclip-labs",
      title: "Developer Community Expansion & Self-Hosted CLI",
      description: "Scale organic developer adoption, documentation hubs, and open-source GitHub engagement.",
      targetMetric: "25,000 GitHub Stars",
      status: "active",
      progressPct: 55,
    },
  ],
};

export const DEFAULT_AGENTS: Record<string, Agent[]> = {
  "comp-founderfit": [
    {
      id: "agent-ff-ceo",
      companyId: "comp-founderfit",
      name: "Dr. Evelyn Vance",
      role: "ceo",
      title: "Chief Strategy Officer & Managing Partner",
      reportsTo: null,
      avatar: "👔",
      systemPrompt:
        "You are the Chief Strategy Officer and CEO of FounderFit Autonomous Strategy Corp. You orchestrate executive decision-making, triage incoming business crises into structured MECE framework workstreams, review deliverables, and direct partner agents.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:50:00Z",
      budgetLimitUsd: 150,
      spentBudgetUsd: 14.3,
      tokensUsed: 142500,
      capabilities: [
        "Executive Problem Triage",
        "MECE Issue Tree Decomposition",
        "C-Suite Recommendation Synthesis",
        "Risk Governance",
      ],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-ff-strategy",
      companyId: "comp-founderfit",
      name: "Julian Thorne",
      role: "strategy_consultant",
      title: "Senior Strategy Partner (Market Entry & Growth)",
      reportsTo: "agent-ff-ceo",
      avatar: "🎯",
      systemPrompt:
        "You are a former Tier-1 Strategy Consulting Partner (McKinsey / BCG) specializing in Market Entry (Should they enter? If yes, how?), Organic vs Inorganic Growth, and Competitive Benchmarking.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:55:00Z",
      budgetLimitUsd: 120,
      spentBudgetUsd: 11.2,
      tokensUsed: 118400,
      capabilities: [
        "Market Entry Feasibility",
        "Ansoff Growth Matrix",
        "Competitive Landscape Mapping",
        "Regulatory & PESTEL Risk Audit",
      ],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-ff-cfo",
      companyId: "comp-founderfit",
      name: "Rohan Patel",
      role: "cfo_analyst",
      title: "VP Corporate Finance & Unit Economics",
      reportsTo: "agent-ff-ceo",
      avatar: "📈",
      systemPrompt:
        "You are a rigorous Corporate Finance and Private Equity Analyst. You dissect EBITDA bridges, unit economics, fixed vs variable cost structures, value-chain procurement waste, and M&A synergy models.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:52:00Z",
      budgetLimitUsd: 100,
      spentBudgetUsd: 8.9,
      tokensUsed: 94300,
      capabilities: [
        "Profitability & Cost Value-Chain Analysis",
        "Unit Economics (LTV/CAC, Contribution Margin)",
        "Pricing Elasticity & Margin Modeling",
        "M&A Due Diligence & Synergies",
      ],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-ff-growth",
      companyId: "comp-founderfit",
      name: "Maya Lin",
      role: "cmo_growth",
      title: "Head of GTM & Product Positioning",
      reportsTo: "agent-ff-ceo",
      avatar: "🚀",
      systemPrompt:
        "You are an elite GTM strategist who executes launches based on the 'Be Selective' doctrine: Customer Segmentation (Demographic, Psychographic, Behavioral), Positioning, Focused Channel Distribution, and Communication Strategy.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:45:00Z",
      budgetLimitUsd: 80,
      spentBudgetUsd: 5.4,
      tokensUsed: 58200,
      capabilities: [
        "GTM Launch Blueprinting",
        "Channel Distribution Strategy",
        "Value-Based Messaging",
        "Customer Acquisition Funnels",
      ],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-ff-ops",
      companyId: "comp-founderfit",
      name: "Vikram Mehta",
      role: "operations_lead",
      title: "VP Operations & Value Chain Optimization",
      reportsTo: "agent-ff-ceo",
      avatar: "⚙️",
      systemPrompt:
        "You are an operational architect specializing in supply chain efficiency, procurement renegotiations, dark-store fulfillment density, and 0-30-90 day tactical execution roadmaps.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:40:00Z",
      budgetLimitUsd: 50,
      spentBudgetUsd: 3.05,
      tokensUsed: 32100,
      capabilities: [
        "Supply Chain & Warehouse Logistics",
        "Last-Mile Cost Compression",
        "0-30-90 Day Execution Roadmaps",
        "SLA & Vendor Governance",
      ],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
  ],
  "comp-paperclip-labs": [
    {
      id: "agent-pcl-ceo",
      companyId: "comp-paperclip-labs",
      name: "Alex Mercer",
      role: "ceo",
      title: "Chief Executive Officer",
      reportsTo: null,
      avatar: "🧠",
      systemPrompt: "You lead Paperclip Autonomous Labs, prioritizing company goals and delegating tickets.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:30:00Z",
      budgetLimitUsd: 400,
      spentBudgetUsd: 45.0,
      tokensUsed: 420000,
      capabilities: ["Product Vision", "Team Orchestration", "Roadmap Prioritization"],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-pcl-cto",
      companyId: "comp-paperclip-labs",
      name: "Marcus Brody",
      role: "cto_architect",
      title: "Principal Systems Architect & CTO",
      reportsTo: "agent-pcl-ceo",
      avatar: "⚡",
      systemPrompt: "You are the CTO responsible for high-performance distributed systems, state engines, and agent runtimes.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:35:00Z",
      budgetLimitUsd: 350,
      spentBudgetUsd: 38.5,
      tokensUsed: 395000,
      capabilities: ["Distributed State Architecture", "Node & TypeScript Runtimes", "Heartbeat Schedulers"],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-pcl-cpo",
      companyId: "comp-paperclip-labs",
      name: "Sarah Jenkins",
      role: "cpo_product",
      title: "VP Product & Developer Experience",
      reportsTo: "agent-pcl-ceo",
      avatar: "💡",
      systemPrompt: "You design developer-friendly workflows, ticket lifecycle UX, and audit interfaces.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:32:00Z",
      budgetLimitUsd: 250,
      spentBudgetUsd: 18.2,
      tokensUsed: 195000,
      capabilities: ["Product Requirements Docs (PRDs)", "User Journey Mapping", "UI/UX Specs"],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
    {
      id: "agent-pcl-cmo",
      companyId: "comp-paperclip-labs",
      name: "Liam O'Connor",
      role: "cmo_growth",
      title: "Head of Developer Marketing & Growth",
      reportsTo: "agent-pcl-ceo",
      avatar: "📢",
      systemPrompt: "You lead developer community adoption, open-source launches, and technical documentation.",
      modelRuntime: "Gemini 1.5 Flash (Auto)",
      status: "idle",
      lastHeartbeatAt: "2026-10-08T01:25:00Z",
      budgetLimitUsd: 200,
      spentBudgetUsd: 12.5,
      tokensUsed: 130000,
      capabilities: ["Technical Blogging", "GitHub Community Growth", "Documentation Architecture"],
      currentTicketId: null,
      isHeartbeatActive: true,
    },
  ],
};

export const DEFAULT_TICKETS: Record<string, Ticket[]> = {
  "comp-founderfit": [
    {
      id: "TICK-FF-101",
      companyId: "comp-founderfit",
      title: "Dark Store Unit Economics & Last-Mile Cost Reduction Blueprint",
      description:
        "Deconstruct the ₹185 per-order fulfilment cost across 140 dark stores into packaging, picker labor, rider incentives, and dead-mileage. Propose dynamic batching and ₹38 margin recovery plan.",
      goalId: "goal-ff-1",
      assigneeId: "agent-ff-cfo",
      priority: "p0_critical",
      status: "done",
      requiresHumanReview: true,
      reviewedByHuman: true,
      checkedOutAt: "2026-10-08T00:40:00Z",
      completedAt: "2026-10-08T00:42:15Z",
      tokensUsed: 4250,
      costUsd: 0.042,
      artifacts: [
        {
          id: "art-ff-101",
          title: "Executive Memo: Dark Store Contribution Margin Turnaround",
          type: "financial_model",
          agentId: "agent-ff-cfo",
          agentName: "Rohan Patel",
          agentRole: "VP Corporate Finance & Unit Economics",
          createdAt: "2026-10-08T00:42:15Z",
          content: `### Executive Financial Audit: Dark Store Unit Economics Turnaround

**Client**: Quick Commerce Hyperlocal Network (140 Dark Stores)  
**Objective**: Eliminate ₹185 per order fulfilment leak to achieve positive unit contribution margin.

#### 1. MECE Value-Chain Cost Breakdown
- **Picker & Sorter In-Store Labor**: ₹48/order (38% idle time during 2:00 PM – 5:00 PM lull).
- **Rider Base & Surge Pay**: ₹68/order (High surge pay due to 10-minute SLA inflexibility).
- **Packaging & Cold Chain Pouches**: ₹26/order (Over-engineered dual-wall insulation for non-perishables).
- **Dark Store Real Estate & Power**: ₹43/order (Fixed rent allocation).

#### 2. Three Immediate Recovery Levers
1. **Algorithmic Dynamic Batching (+₹22/order recovery)**:
   - Allow 18-minute delivery windows instead of 10-minute for orders within a 600m cluster, unlocking 2.4 deliveries/trip instead of 1.1.
2. **Packaging Tier Optimization (+₹11/order recovery)**:
   - Introduce single-ply recycled kraft pouches for ambient grocery orders, slashing packaging cost by 42%.
3. **Flexible Shift Staffing (+₹14/order recovery)**:
   - Shift 30% of permanent in-store sorters to variable peak-hour flex contracts (7:00 AM - 11:00 AM, 6:00 PM - 11:00 PM).

#### 3. Financial Impact Projection
- **Net Margin Recovery**: +₹47 per delivered order.
- **Monthly Run-rate Savings**: ₹3.29 Crore across 140 dark stores.
- **Breakeven Timeline**: 45 days from rollout.`,
        },
      ],
      logs: [
        {
          id: "log-1",
          timestamp: "2026-10-08T00:40:00Z",
          agentId: "agent-ff-cfo",
          agentName: "Rohan Patel",
          ticketId: "TICK-FF-101",
          phase: "heartbeat",
          message: "Agent received scheduled heartbeat signal. Scanning assigned tickets.",
        },
        {
          id: "log-2",
          timestamp: "2026-10-08T00:40:05Z",
          agentId: "agent-ff-cfo",
          agentName: "Rohan Patel",
          ticketId: "TICK-FF-101",
          phase: "checkout",
          message: "Atomic Checkout: Acquired exclusive execution lock on TICK-FF-101.",
        },
        {
          id: "log-3",
          timestamp: "2026-10-08T00:41:10Z",
          agentId: "agent-ff-cfo",
          agentName: "Rohan Patel",
          ticketId: "TICK-FF-101",
          phase: "reasoning",
          message:
            "Decomposed cost buckets into In-Store Picking, Fleet Dispatch, Packaging, and Fixed Capex. Formulated 3 margin recovery interventions.",
        },
        {
          id: "log-4",
          timestamp: "2026-10-08T00:42:00Z",
          agentId: "agent-ff-cfo",
          agentName: "Rohan Patel",
          ticketId: "TICK-FF-101",
          phase: "artifact",
          message: "Generated executive financial model deliverable 'Dark Store Turnaround Memo'.",
        },
        {
          id: "log-5",
          timestamp: "2026-10-08T00:42:15Z",
          agentId: "agent-ff-cfo",
          agentName: "Rohan Patel",
          ticketId: "TICK-FF-101",
          phase: "budget_debit",
          message: "Debited 4,250 tokens ($0.042) against Agent budget. Returning to standby.",
        },
      ],
    },
    {
      id: "TICK-FF-102",
      companyId: "comp-founderfit",
      title: "UAE & Saudi Market Entry Strategic Synthesis",
      description:
        "Run comprehensive Market Entry Framework analysis: assess TAM, regulatory import approvals (ESMA / SFDA), distribution channel partner selection (Noon, Amazon, Sephora ME) vs DTC.",
      goalId: "goal-ff-2",
      assigneeId: "agent-ff-strategy",
      priority: "p1_high",
      status: "assigned",
      requiresHumanReview: true,
      reviewedByHuman: false,
      checkedOutAt: null,
      completedAt: null,
      tokensUsed: 0,
      costUsd: 0,
      artifacts: [],
      logs: [],
    },
    {
      id: "TICK-FF-103",
      companyId: "comp-founderfit",
      title: "GTM Selective Channel Launch Plan for GCC Expansion",
      description:
        "Draft customer segmentation matrix and omnichannel influencer seeding strategy adhering to the 'Be Selective' rule before broader roll-out.",
      goalId: "goal-ff-2",
      assigneeId: "agent-ff-growth",
      priority: "p2_medium",
      status: "backlog",
      requiresHumanReview: false,
      reviewedByHuman: false,
      checkedOutAt: null,
      completedAt: null,
      tokensUsed: 0,
      costUsd: 0,
      artifacts: [],
      logs: [],
    },
    {
      id: "TICK-FF-104",
      companyId: "comp-founderfit",
      title: "Enterprise 3-Tier Pricing Model & Value-Based Metric Design",
      description:
        "Formulate SaaS pricing tiers (Starter, Growth, Enterprise) replacing unmetered flat seats with hybrid platform fee + active agent usage units.",
      goalId: "goal-ff-3",
      assigneeId: "agent-ff-cfo",
      priority: "p1_high",
      status: "backlog",
      requiresHumanReview: true,
      reviewedByHuman: false,
      checkedOutAt: null,
      completedAt: null,
      tokensUsed: 0,
      costUsd: 0,
      artifacts: [],
      logs: [],
    },
  ],
  "comp-paperclip-labs": [
    {
      id: "TICK-PCL-201",
      companyId: "comp-paperclip-labs",
      title: "Build Atomic Heartbeat Checkout & Lock Recovery Protocol",
      description:
        "Implement concurrency control preventing dual-agent execution collision using state locks and automatic timeout recovery.",
      goalId: "goal-pcl-1",
      assigneeId: "agent-pcl-cto",
      priority: "p0_critical",
      status: "in_progress",
      requiresHumanReview: false,
      reviewedByHuman: false,
      checkedOutAt: "2026-10-08T01:35:00Z",
      completedAt: null,
      tokensUsed: 3100,
      costUsd: 0.031,
      artifacts: [],
      logs: [
        {
          id: "log-pcl-1",
          timestamp: "2026-10-08T01:35:00Z",
          agentId: "agent-pcl-cto",
          agentName: "Marcus Brody",
          ticketId: "TICK-PCL-201",
          phase: "heartbeat",
          message: "Heartbeat loop cycle activated. Ticket TICK-PCL-201 inspected.",
        },
        {
          id: "log-pcl-2",
          timestamp: "2026-10-08T01:35:05Z",
          agentId: "agent-pcl-cto",
          agentName: "Marcus Brody",
          ticketId: "TICK-PCL-201",
          phase: "checkout",
          message: "Checked out ticket atomically. Lock acquired.",
        },
        {
          id: "log-pcl-3",
          timestamp: "2026-10-08T01:36:00Z",
          agentId: "agent-pcl-cto",
          agentName: "Marcus Brody",
          ticketId: "TICK-PCL-201",
          phase: "reasoning",
          message: "Formulating atomic checkout state machine and Redis/PostgreSQL lock pattern...",
        },
      ],
    },
    {
      id: "TICK-PCL-202",
      companyId: "comp-paperclip-labs",
      title: "Interactive Org Chart & Agent Hierarchy Visualizer Spec",
      description: "Define PRD and visual tree specs showing reporting lines, budget meters, and heartbeat statuses.",
      goalId: "goal-pcl-1",
      assigneeId: "agent-pcl-cpo",
      priority: "p1_high",
      status: "backlog",
      requiresHumanReview: true,
      reviewedByHuman: false,
      checkedOutAt: null,
      completedAt: null,
      tokensUsed: 0,
      costUsd: 0,
      artifacts: [],
      logs: [],
    },
  ],
};
